### ISSUE TITLE
容器之间的网络问题

### ISSUE THREAD

**Issue by hezygo** [Boris-code/feaplat#1]
### 在成功构建镜像后，启动时报错
`Error response from daemon: Could not attach to network feaplat: rpc error: code = PermissionDenied desc = network feaplat not manually attachable`

需要先初始化swarm

1. `docker swarm init`
2.  `docker network create --driver overlay --attachable feaplat`  [解决方式参考](https://blog.csdn.net/liwenhoho/article/details/111292446)
3. 如果你还是不行：就先强制清空 `docker swarm leave -f`  然后重复1，2

**Comment by Boris-code** [comment]
多谢，已改正
